#!/usr/bin/env bash
# This script displays the PID and name of processes containing 'bash' (without ps).

pgrep -l bas#!/usr/bin/env bash
# This script displays the PID and name of processes containing 'bash' (without ps).

pgrep -l bash
